import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="fixed top-0 bottom-0 flex h-screen w-2/16 bg-emerald-400">
          <nav className="flex flex-col items-start space-y-2 mt-4">
            <Link href="/" className="text-gray-800 hover:underline ml-4">
              Home
            </Link>
            <Link
              href="/pages/Profile"
              className="text-gray-800 hover:underline ml-4"
            >
              Profil
            </Link>
            <Link href="/pages/Skills" className="text-gray-800 hover:underline ml-4">
              Kompentencer
            </Link>
            <Link
              href="/pages/Projects"
              className="text-gray-800 hover:underline ml-4"
            >
              Projekter
            </Link>
            <Link
              href="/pages/Contact"
              className="text-gray-800 hover:underline ml-4"
            >
              Kontakt
            </Link>
            <Link href="/pages/Test" className="text-gray-800 hover:underline ml-4">
              Test
            </Link>
          </nav>
        </div>
        {children}
        <nav></nav>
      </body>
    </html>
  );
}
